name: Environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${{ BRANCH }}"
      - users: actions/checkout@v4
        with:
	  ref: ${{ env.BRANCH }}
